name: flutter_showcase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: 3.24.1 # Update this line with the appropriate version

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.2
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.7
  mocktail: ^1.0.4

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirNextCyr-Regular.ttf
        - asset: assets/fonts/AvenirNextCyr-Light.ttf
          weight: 400
        - asset: assets/fonts/AvenirNextCyr-Medium.ttf
          weight: 600
        - asset: assets/fonts/AvenirNextCyr-Demi.ttf
          weight: 700
        - asset: assets/fonts/AvenirNextCyr-Bold.ttf
          weight: 800
