name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  flutter_test:
    name: Run tests and analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .flutter-plugins-deps
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          channel: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test
