name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  flutter_test:
    name: Run tests and analysis
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Set up Flutter using the version from pubspec.yaml
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml # Path to the pubspec.yaml
          channel: stable # Use the stable channel

      # Run Flutter commands
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Check Flutter formatting
        run: flutter format --dry-run --set-exit-if-changed

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test
