name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  flutter_test:
    name: Run tests and analysis
    runs-on: ubuntu-latest
    steps:
      # Clone the repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Set up Flutter using the version from pubspec.yaml
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml # Use the updated pubspec.yaml
          channel: stable

      # Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Run Flutter tests
      - name: Run Flutter tests
        run: flutter test
