name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  flutter_test:
    name: Run tests and analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable" # Specify the Flutter version or channel
      - run: flutter pub get
      - run: flutter format --dry-run --set-dartfmt
      - run: flutter analyze
      - run: flutter test
